## 2.1.1 入门

首先，我们从MXNet导入np（numpy）模块和npx（numpy_extension）模块。np模块包含NumPy支持的函数；
而npx模块包含一组扩展函数，用来在类似NumPy的环境中实现深度学习开发。当使用张量时，几乎总是会
调用set_np函数，这是为了兼容MXNet的其他张量处理组件。

In [2]:
from mxnet import np, npx

npx.set_np()

张量表示一个由数值组成的数组，这个数组可能有多个维度。具有一个轴的张量对应数学上的向量（vector）；
具有两个轴的张量对应数学上的矩阵（matrix）；具有两个轴以上的张量没有特殊的数学名称。

首先，我们可以使用 arange 创建一个行向量 x。这个行向量包含以0开始的前12个整数，它们默认创建为浮
点数。

In [3]:
x = np.arange(12)
x

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

张量形状

In [4]:
x.shape

(12,)

张量元素总数

In [5]:
x.size

12

改变一个张量的形状而不改变元素数量和元素值，可以调用reshape函数

In [6]:
X = x.reshape(3, 4)
X

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

我们不需要通过手动指定每个维度来改变形状。也就是说，如果我们的目标形状是（高度,宽度），那么在
知道宽度后，高度会被自动计算得出，在高度出填-1

In [7]:
X = x.reshape(3, -1)
X

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

希望使用全0、全1、其他常量，或者从特定分布中随机采样的数字来初始化矩阵。

In [8]:
np.zeros((2, 3 ,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [9]:
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

有时我们想通过从某个特定的概率分布中随机采样来得到张量中每个元素的值。

In [10]:
np.random.normal(0, 1, size=(100,100))

array([[ 2.2122064 ,  1.1630787 ,  0.7740038 , ..., -1.3549325 ,
        -0.45481315, -0.95748407],
       [ 0.32510808, -0.72485566, -1.3002341 , ..., -1.2138013 ,
        -0.5669272 ,  2.3999705 ],
       [-0.02392192, -0.38509107,  1.0756664 , ..., -1.8610498 ,
        -1.3251876 , -0.46895587],
       ...,
       [ 0.5021908 ,  0.62810886,  0.44951567, ..., -0.47523203,
        -0.9926243 , -0.7608889 ],
       [-1.267435  ,  0.68881726,  1.4059061 , ...,  1.7538831 ,
        -0.7416085 ,  0.5849303 ],
       [ 0.7865544 ,  0.03578907,  2.1154199 , ..., -0.98873866,
         0.9117474 ,  0.9378694 ]])

我们还可以通过提供包含数值的Python列表（或嵌套列表），来为所需张量中的每个元素赋予确定值。在这
里，最外层的列表对应于轴0，内层的列表对应于轴1。

In [11]:
np.array([[2,1,4,3], [1,2,3,4], [4,3,2,1]])

array([[2., 1., 4., 3.],
       [1., 2., 3., 4.],
       [4., 3., 2., 1.]])

## 2.1.2 运算符

In [12]:
x = np.array([1, 2, 4, 8])
y = np.array([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y # **运算符是求幂运算

(array([ 3.,  4.,  6., 10.]),
 array([-1.,  0.,  2.,  6.]),
 array([ 2.,  4.,  8., 16.]),
 array([0.5, 1. , 2. , 4. ]),
 array([ 1.,  4., 16., 64.]))

In [13]:
np.exp(x)

array([2.7182817e+00, 7.3890562e+00, 5.4598148e+01, 2.9809580e+03])

In [14]:
X = np.arange(12).reshape(3, 4)
Y = np.array([[2,1,4,3], [1,2,3,4], [4,3,2,1]])
np.concatenate([X, Y], axis=0), np.concatenate([X, Y], axis=1)

(array([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]]),
 array([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [15]:
X == Y

array([[False,  True, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [16]:
X.sum()

array(66.)

## 2.1.3 广播机制